Repository AY2021S2-CS2113T-W09-1/tp, pull requests merged in 2021-03, with the labels that each got.

#47 Implement remove command
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
Labels: type.Task

#48 Branch command view v1
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Task

#50 Refactored Duke class to reflect the style presented in A-MoreOOP
  src/main/java/seedu/duke/Duke.java
Labels: type.Enhancement

#55 Update validateAmount to fix parsing a double.
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/common/Validators.java
Labels: type.Bug

#62 Implement Index Validation for Remove Command
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
Labels: type.Enhancement, type.Task

#65 Update Help Command
  src/main/java/seedu/duke/ui/HelpPage.java
Labels: type.Task

#66 Add Index Validation for Return Command
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
Labels: type.Enhancement, type.Task

#68 Branch refine validate index
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/common/Validators.java
Labels: type.Enhancement

#69 Integration Check 1
  src/main/java/seedu/duke/record/Loan.java
Labels: type.Enhancement

#71 Update toString for Record Classes and minor UI changes
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/record/Expense.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/Saving.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/RecordListTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#70 Add JUnit test cases for ParserHandler
  src/test/java/seedu/duke/parser/ParserHandlerTest.java
Labels: type.Enhancement

#75 Modify areas with variable "amount"
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/record/Expense.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/Saving.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/RecordListTest.java
Labels: type.Bug

#77 Jonah branch storage load
  finux.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/exception/FileLoadingException.java
  src/main/java/seedu/duke/exception/InvalidCommandException.java
  src/main/java/seedu/duke/exception/InvalidFileInputException.java
  src/main/java/seedu/duke/parser/ParserHandler.java
  src/main/java/seedu/duke/record/Expense.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/record/Saving.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: severity.High, type.Task

#78 Branch utils update
  src/main/java/seedu/duke/command/Utils.java
Labels: documentation, type.Enhancement

#80 Add JavaDoc (See details)
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/Utils.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/parser/ParserHandler.java
  src/main/java/seedu/duke/ui/HelpPage.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation

#82 refactor command class for add, list, remove, return, view.
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
Labels: type.Enhancement

#84 Add Junit Tests for RemoveCommand
  finux.txt
  src/test/java/seedu/duke/command/RemoveCommandTest.java
Labels: type.Task, type.Test

#87 Fixed load method
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: severity.High, type.Bug

#90 Add JavaDoc, Assertion, Renaming
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
Labels: type.Enhancement

#91 Branch Add Assertions
  src/main/java/seedu/duke/command/Utils.java
Labels: type.Enhancement

#96 Add skeleton code for CreditScoreCommand
  src/main/java/seedu/duke/command/CreditScoreCommand.java
  src/main/java/seedu/duke/common/Validators.java
Labels: type.Task

#101 Implement partially CreditScoreCommand
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/CreditScoreCommand.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/record/Expense.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/Saving.java
Labels: type.Task

#103 Branch parser v2
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/parser/ParserHandler.java
  src/test/java/seedu/duke/command/UtilsTest.java
Labels: type.Enhancement, type.Task

#107 update help command, validation of help command
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/Utils.java
  src/main/java/seedu/duke/ui/HelpPage.java
Labels: type.Enhancement, type.Task

#108 Fix bug for parsing help addall
  src/main/java/seedu/duke/command/Utils.java
Labels: type.Bug

#109 Add skeleton for UG.
  docs/README.md
  docs/UserGuide.md
Labels: documentation, type.Task

#113 add junit test for view command
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: type.Test

#115 Added assertions
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation, type.Enhancement

#116 update view method for v2.0
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Enhancement

#117 Update UserGuide on view and exit section.
  docs/UserGuide.md
Labels: documentation

#120 Branch Update UG
  docs/UserGuide.md
Labels: documentation

#121 Branch Skeleton DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/style.puml
  docs/img/ArchitectureDiagram.png
Labels: documentation

#122 Updated UG for Storage Class
  docs/UserGuide.md
  docs/img/Failed_Load_Example_Output.jpg
  docs/img/New_File_Creation_Example.jpg
  docs/img/Successful_Load_Example.jpg
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation

#124 Update User Guide
  docs/UserGuide.md
  docs/img/Remove_Example_Output.png
Labels: documentation

#125 Update Help Page
  src/main/java/seedu/duke/ui/HelpPage.java
Labels: type.Enhancement

#127 Modify DG Skeleton, Update DG
  docs/DeveloperGuide.md
Labels: documentation

#126 Update parser class to become more object oriented.
  docs/diagrams/ParserHandlerClassDiagram.puml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/ParserHandler.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/ReturnCommandTest.java
  src/test/java/seedu/duke/command/UtilsTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
  src/test/java/seedu/duke/parser/ParserHandlerTest.java
Labels: type.Enhancement

#128 Branch Update UG
  docs/UserGuide.md
Labels: documentation

#123 Branch Update CommandHandler
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/ReturnCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: type.Enhancement

#130 Update DG Architecture in Design section
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandLooperSequenceDiagram.puml
  docs/diagrams/InitializationSequenceDiagram.puml
  docs/img/ArchitectureDiagram.png
  docs/img/CommandLooperSequenceDiagram.png
  docs/img/InitializationSequenceDiagram.png
Labels: documentation

#131 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/RemoveFeatureSequenceDiagram.puml
  docs/diagrams/UIComponentDiagram.puml
  docs/img/LoginPageExampleOutput.png
  docs/img/RemoveExampleOutput.png
  docs/img/RemoveFeatureSequenceDiagram.png
  docs/img/UIComponentDiagram.png
  src/main/java/seedu/duke/command/Utils.java
Labels: documentation, type.Enhancement

#132 Update UG with screenshots
  docs/UserGuide.md
  docs/img/Add_Expense_Example_Output.png
  docs/img/Add_Loan_Example_Output.png
  docs/img/Add_Savings_Example_Output.png
  src/main/java/seedu/duke/command/AddCommand.java
Labels: documentation

#133 Branch user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewFeatureSequenceDiagram.puml
  docs/img/Help_Example_Output.jpg
  docs/img/View Example Output.jpg
  docs/img/View_Example_Output.jpg
  src/main/java/seedu/duke/ui/HelpPage.java
Labels: documentation

#135 Update UG
  docs/UserGuide.md
  docs/img/CreditScoreExampleOutput.jpg
Labels: documentation

#137 Change AddCommand Output Pictures
  docs/img/Add_Expense_Example_Output.png
  docs/img/Add_Loan_Example_Output.png
  docs/img/Add_Savings_Example_Output.png
Labels: documentation

#138 Updated Storage and Loan class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: severity.Medium, type.Enhancement

#139 Update View Feature Implementation for DG
  docs/DeveloperGuide.md
Labels: documentation

#140 Implements FinuxLogger
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/common/FinuxLogger.java
Labels: type.Enhancement

#142 Update UG Diagrams, validateIndex Logger
  docs/UserGuide.md
  docs/img/AddExpenseExampleOutput.jpg
  docs/img/AddLoanExampleOutput.jpg
  docs/img/AddSavingExampleOutput.jpg
  docs/img/Add_Expense_Example_Output.png
  docs/img/Add_Loan_Example_Output.png
  docs/img/Add_Savings_Example_Output.png
  docs/img/CreditScoreExampleOutput.jpg
  docs/img/FailedLoadExampleOutput.jpg
  docs/img/Failed_Load_Example_Output.jpg
  docs/img/HelpExampleOutput.jpg
  docs/img/Help_Example_Output.jpg
  docs/img/ListExampleOutput.jpg
  docs/img/NewFileCreationExampleOutput.jpg
  docs/img/New_File_Creation_Example.jpg
  docs/img/RemoveExampleOutput.jpg
  docs/img/RemoveExampleOutput.png
  docs/img/ReturnExampleOutput.jpg
  docs/img/SuccessfulLoadExampleOutput.jpg
  docs/img/Successful_Load_Example.jpg
  docs/img/ViewExampleOutput.jpg
  docs/img/View_Example_Output.jpg
  src/main/java/seedu/duke/common/Validators.java
Labels: type.Enhancement

#151 Update DG for Command and CommandHandler components
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/CommandHandlerClassDiagram.puml
  docs/diagrams/CommandHandlerSequenceDiagram.puml
  docs/diagrams/CommandLooperSequenceDiagram.puml
  docs/img/CommandClassDiagram.png
  docs/img/CommandHandlerClassDiagram.png
  docs/img/CommandHandlerSequenceDiagram.png
  docs/img/CommandLooperSequenceDiagram.png
  src/main/java/seedu/duke/Finux.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/ExitCommand.java
Labels: documentation

#152 Update UG, DG and Guard Clause
  docs/UserGuide.md
  docs/diagrams/RemoveFeatureSequenceDiagram.puml
  docs/diagrams/UIComponentDiagram.puml
  docs/img/AddExpenseExampleOutput.jpg
  docs/img/AddLoanExampleOutput.jpg
  docs/img/AddSavingExampleOutput.jpg
  docs/img/CreditScoreExampleOutput.jpg
  docs/img/ExitExampleOutput.jpg
  docs/img/FailedLoadExampleOutput.jpg
  docs/img/ListExpenseExampleOutput.jpg
  docs/img/ListLoanExampleOutput.jpg
  docs/img/ListSavingExampleOutput.jpg
  docs/img/NewFileCreationExampleOutput.jpg
  docs/img/RemoveExampleOutput.jpg
  docs/img/RemoveFeatureSequenceDiagram.png
  docs/img/ReturnExampleOutput.jpg
  docs/img/SuccessfulLoadExampleOutput.jpg
  docs/img/UIComponentDiagram.png
  docs/img/ViewExampleOutput.jpg
  docs/img/ViewExpenseExampleOutput.jpg
  docs/img/ViewLoanExampleOutput.jpg
  docs/img/ViewSavingExampleOutput.jpg
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/record/Record.java
Labels: type.Enhancement

#154 Branch creditscore refactor
  src/main/java/seedu/duke/Finux.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CreditScoreCommand.java
  src/main/java/seedu/duke/command/CreditScoreMap.java
  src/main/java/seedu/duke/command/CreditScoreReturnedLoansMap.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/Utils.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/ReturnCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: type.Enhancement
