Repository AY2021S2-CS2113T-W09-1/tp, pull requests merged in 2021-04, with the labels that each got.

#163 update DG to fix 3.7 line break
  docs/DeveloperGuide.md
Labels: documentation

#164 Update DG for Ui
  docs/DeveloperGuide.md
  docs/diagrams/UIComponentDiagram.puml
  docs/img/UIComponentDiagram.png
Labels: documentation, type.Enhancement

#162 Improve userguide
  docs/UserGuide.md
Labels: documentation, type.Enhancement

#165 Fix diagram errors and add more descriptions to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureSequenceDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/CommandHandlerClassDiagram.puml
  docs/diagrams/CommandHandlerSequenceDiagram.puml
  docs/diagrams/CommandLooperSequenceDiagram.puml
  docs/diagrams/InitializationSequenceDiagram.puml
  docs/img/AddFeatureSequenceDiagram.png
  docs/img/CommandClassDiagram.png
  docs/img/CommandHandlerClassDiagram.png
  docs/img/CommandHandlerSequenceDiagram.png
  docs/img/CommandLooperSequenceDiagram.png
  docs/img/InitializationSequenceDiagram.png
Labels: documentation

#190 Add list -a
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/common/RecordType.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation, type.Enhancement

#192 update UG for view section
  docs/UserGuide.md
Labels: documentation

#193 Update DateFormats and ResolverStyle
  src/main/java/seedu/duke/common/Validators.java
  src/test/java/seedu/duke/common/ValidatorsTest.java
Labels: type.BugFix

#194 Update DG for manual testing
  docs/DeveloperGuide.md
  docs/img/ListAllExampleOutput.jpg
  docs/img/ViewAllExampleOutput.jpg
Labels: documentation

#195 Jonah branch dg
  docs/DeveloperGuide.md
  docs/diagrams/StorageSequenceDiagramLoad.puml
  docs/diagrams/StorageSequenceDiagramSave.puml
  docs/img/StorageSequenceDiagramLoad.png
  docs/img/StorageSequenceDiagramSave.png
  src/main/java/seedu/duke/storage/Storage.java
Labels: documentation

#198 update help after PE dry run feed back
  src/main/java/seedu/duke/ui/HelpPage.java
Labels: type.Enhancement

#199 Fix file writing bug of creditscore feature
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: type.BugFix

#200 Add Andy's PPP
  docs/AboutUs.md
  docs/team/LeeHanYongAndy.md
  docs/team/johndoe.md
Labels: documentation

#209 Jonah branch j-unit
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/CreditScoreCommandTest.java
  src/test/java/seedu/duke/command/ReturnCommandTest.java
Labels: type.Test

#210 Jonah branch ppp
  docs/team/JonahThamWenLong.md
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
Labels: documentation, type.BugFix

#208 Add Refactor and Test for command.Utils class
  src/main/java/seedu/duke/command/Utils.java
  src/test/java/seedu/duke/command/UtilsTest.java
Labels: type.Enhancement

#213 First draft for PPP
  docs/team/gerardtwk.md
Labels: documentation

#212 update DG for v2.1
  docs/DeveloperGuide.md
  docs/diagrams/ViewFeatureSequenceDiagram.puml
  docs/img/ViewFeatureSequenceDiagram.png
Labels: documentation

#214 Add PPP and update UG and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/CommandClassDiagram2.puml
  docs/img/AddCommandClassDiagram.png
  docs/img/CommandClassDiagram.png
  docs/img/CommandClassDiagram2.png
  docs/team/marklowsk.md
Labels: documentation, type.BugFix

#215 v2.1 changes
  docs/AboutUs.md
  docs/UserGuide.md
  docs/img/AddExpenseExampleOutput.jpg
  docs/img/AddExpenseExampleOutput.png
  docs/img/AddLoanExampleOutput.jpg
  docs/img/AddLoanExampleOutput.png
  docs/img/AddSavingExampleOutput.jpg
  docs/img/AddSavingExampleOutput.png
  docs/img/CreditScoreExampleOutput.jpg
  docs/img/CreditScoreExampleOutput.png
  docs/img/ExitExampleOutput.jpg
  docs/img/ExitExampleOutput.png
  docs/img/FailedLoadExampleOutput.jpg
  docs/img/FailedLoadExampleOutput.png
  docs/img/HelpAllExampleOutput.png
  docs/img/HelpExampleOutput.jpg
  docs/img/HelpExampleOutput.png
  docs/img/ListAllExampleOutput.jpg
  docs/img/ListAllExampleOutput.png
  docs/img/ListExpenseExampleOutput.jpg
  docs/img/ListExpenseExampleOutput.png
  docs/img/ListLoanExampleOutput.jpg
  docs/img/ListLoanExampleOutput.png
  docs/img/NewFileCreationExampleOutput.jpg
  docs/img/NewFileCreationExampleOutput.png
  docs/img/RemoveExampleOutput.jpg
  docs/img/RemoveExampleOutput.png
  docs/img/ReturnExampleOutput.jpg
  docs/img/ReturnExampleOutput.png
  docs/img/SuccessfulLoadExampleOutput.jpg
  docs/img/SuccessfulLoadExampleOutput.png
  docs/img/ViewAllExampleOutput.jpg
  docs/img/ViewAllExampleOutput.png
  docs/img/ViewExpenseExampleOutput.jpg
  docs/img/ViewExpenseExampleOutput.png
  docs/img/ViewLoanExampleOutput.jpg
  docs/img/ViewLoanExampleOutput.png
  docs/img/ViewSavingExampleOutput.jpg
  docs/img/ViewSavingExampleOutput.png
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/record/Expense.java
  src/main/java/seedu/duke/record/Loan.java
  src/main/java/seedu/duke/record/Record.java
  src/main/java/seedu/duke/record/Saving.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/CreditScoreCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RemoveCommandTest.java
  src/test/java/seedu/duke/command/ReturnCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
  src/test/java/seedu/duke/record/RecordListTest.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, type.Enhancement

#216 Add PPP
  docs/img/ListSavingExampleOutput.jpg
  docs/img/ListSavingExampleOutput.png
  docs/team/tzexern.md
Labels: documentation, type.Enhancement

#217 update UG on help section
  docs/UserGuide.md
Labels: type.Enhancement

#218 Modify DG Update Ui and Add Messages.java
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/CommandClassDiagram2.puml
  docs/img/AddCommandClassDiagram.png
  docs/img/ArchitectureDiagram.png
  docs/img/CommandClassDiagram.png
  docs/img/CommandClassDiagram2.png
  src/main/java/seedu/duke/Finux.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation, type.Enhancement

#219 update ParserHandler variable names
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/parser/ParserHandler.java
Labels: documentation

#220 Add ListFeature for DG
  docs/DeveloperGuide.md
  docs/diagrams/ListFeatureSequenceDiagram.puml
  docs/diagrams/ViewFeatureSequenceDiagram.puml
  docs/img/ListFeatureSequenceDiagram.png
  docs/img/ViewFeatureSequenceDiagram.png
Labels: documentation

#222 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/RemoveFeatureSequenceDiagram.puml
  docs/diagrams/ReturnFeatureSequenceDiagram.puml
  docs/img/RemoveFeatureSequenceDiagram.png
  docs/img/ReturnFeatureSequenceDiagram.png
Labels: documentation

#224 Small DG updates and code refactor
  docs/diagrams/AddFeatureSequenceDiagram.puml
  docs/img/AddFeatureSequenceDiagram.png
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/common/Validators.java
Labels: documentation, type.Enhancement

#225 Update Help Screenshot
  docs/img/HelpAllExampleOutput.png
  docs/img/HelpExampleOutput.png
Labels: type.Enhancement

#234 Update errors in DG and Code
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureSequenceDiagram.puml
  docs/diagrams/CommandHandlerSequenceDiagram.puml
  docs/diagrams/CommandLooperSequenceDiagram.puml
  docs/img/AddFeatureSequenceDiagram.png
  docs/img/CommandHandlerSequenceDiagram.png
  docs/img/CommandLooperSequenceDiagram.png
Labels: documentation

#235 CreditScoreCommand and RecordList developer guide documentation
  docs/DeveloperGuide.md
  docs/diagrams/CreditScoreFeatureSequenceDiagram.puml
  docs/diagrams/RecordListClassDiagram.puml
  docs/img/CreditScoreFeatureSequenceDiagram.png
  docs/img/RecordListClassDiagram.png
Labels: documentation

#236 Update DG
  docs/DeveloperGuide.md
  docs/img/LoginPageExampleOutput.png
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/common/Validators.java
Labels: type.Enhancement

#237 Update minor DG error
  docs/DeveloperGuide.md
  docs/team/leehanyongandy.md
Labels: documentation

#238 Fix a few mistakes in CreditScoreCommand sequence diagram
  docs/diagrams/CreditScoreFeatureSequenceDiagram.puml
  docs/img/CreditScoreFeatureSequenceDiagram.png
Labels: documentation, type.BugFix

#240 Update DG for new component, UG screenshot, UML minor change
  docs/DeveloperGuide.md
  docs/diagrams/ReturnFeatureSequenceDiagram.puml
  docs/img/HelpAllExampleOutput.png
  docs/team/tzexern.md
Labels: type.Enhancement

#241 Refactor Magic Strings
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/common/Messages.java
Labels: type.Enhancement

#243 Paraphrase documentation for CreditScore feature
  docs/DeveloperGuide.md
Labels: documentation, type.Enhancement

#244 Minor fix to note section in RecordList class diagram
  docs/diagrams/RecordListClassDiagram.puml
  docs/img/RecordListClassDiagram.png
  src/main/java/seedu/duke/record/Record.java
Labels: documentation, type.Enhancement

#242 Branch Fixes for v2.1
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureSequenceDiagram.puml
  docs/img/AddFeatureSequenceDiagram.png
  docs/team/marklowsk.md
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/Utils.java
  src/main/java/seedu/duke/common/ArgumentType.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/common/FinuxLogger.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/common/RecordType.java
  src/main/java/seedu/duke/common/Validators.java
  src/main/java/seedu/duke/exception/CommandException.java
  src/main/java/seedu/duke/exception/CustomException.java
  src/main/java/seedu/duke/exception/FileLoadingException.java
  src/main/java/seedu/duke/exception/InvalidFileInputException.java
Labels: documentation, type.Enhancement

#245 Update PPP
  docs/team/tzexern.md
Labels: type.Enhancement

#247 Update PPP
  docs/diagrams/RemoveFeatureSequenceDiagram.puml
  docs/img/RemoveFeatureSequenceDiagram.png
  docs/team/tzexern.md
Labels: documentation

#249 Update PPP to reduce pages
  docs/team/marklowsk.md
Labels: documentation

#254 Update PPP again 2
  docs/team/tzexern.md
Labels: documentation

#255 Updated PPP 3
  docs/team/jonahtwl.md
Labels: documentation

#256 Update Bugs After Last Smoke Test
  docs/team/marklowsk.md
  src/main/java/seedu/duke/command/CreditScoreCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/Utils.java
  src/main/java/seedu/duke/parser/ParserHandler.java
Labels: type.BugFix

#257 Add developer guide documentation for CreditScoreReturnedLoansMap
  docs/DeveloperGuide.md
  docs/diagrams/CreditScoreReturnedLoansMap.puml
  docs/img/CreditScoreReturnedLoansMapClassDiagram.png
Labels: documentation

#258 update DG typo fix
  docs/DeveloperGuide.md
Labels: documentation

#261 Updated PUML diagram
  docs/diagrams/CreditScoreFeatureSequenceDiagram.puml
  docs/img/CreditScoreFeatureSequenceDiagram.png
Labels: documentation

#262 Updated PUML diagrams again
  docs/diagrams/StorageSequenceDiagramLoad.puml
  docs/diagrams/StorageSequenceDiagramSave.puml
  docs/img/StorageSequenceDiagramLoad.png
  docs/img/StorageSequenceDiagramSave.png
Labels: documentation

#263 Update PUML once again
  docs/diagrams/StorageSequenceDiagramLoad.puml
  docs/img/StorageSequenceDiagramLoad.png
Labels: documentation

#260 Java docs for undocumented classes
  src/main/java/seedu/duke/Finux.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandHandler.java
  src/main/java/seedu/duke/command/CreditScoreCommand.java
  src/main/java/seedu/duke/command/CreditScoreReturnedLoansMap.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/RemoveCommand.java
  src/main/java/seedu/duke/command/ReturnCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/record/RecordList.java
  src/main/java/seedu/duke/storage/Storage.java
Labels: documentation
